### ISSUE TITLE
Uncategorized items (no category) get moved into wrong category

### ISSUE THREAD

**Issue by mahagr** [fastslack/jUpgrade#29]
This bug is at least in articles, but most likely apply to every other component that has categories, too.

If Joomla 1.5 site had articles that were not assigned to any category, they get moved to the first valid category, which changes how the site behaves.

```
Title:'My Article' Section: '', Category: ''
```

becomes:

```
Title:'My Article' Category: 'My Products'
```

where it should be:

```
Title:'My Article' Category: 'Uncategorized'
```

**Comment by fastslack** [comment]
This issue is fixed into yout latest pull request?

**Comment by mahagr** [comment]
I think that the issue is still in there. Need to take a look into it.
